# Generated by Django 4.2.6 on 2023-11-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burhan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='On_road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('road', models.CharField(max_length=100)),
                ('bike', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('d_no', models.CharField(max_length=100)),
                ('s_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('dis', models.CharField(max_length=100)),
                ('mob1', models.CharField(max_length=100)),
                ('mob2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
    ]
